; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter =
	+<*>
build_flags =
	-D GROVA_BUILD_ENV=\"esp32dev\"
lib_deps = 
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit AHTX0@^2.0.5
	knolleary/PubSubClient@^2.8
upload_protocol = esptool

[env:esp32dev_ota]
extends = env:esp32dev
build_flags =
	-D GROVA_BUILD_ENV=\"esp32dev_ota\"
upload_protocol = espota
upload_port = 192.168.1.70

[env:grova_cube_001_dht]
extends = env:esp32dev
build_flags =
	-D GROVA_BUILD_ENV=\"grova_cube_001_dht\"
	-D GROVA_CUBE_ID_OVERRIDE=\"grova-cube-001\"
	-D OTA_HOSTNAME=\"grova-cube-001\"
upload_protocol = esptool

[env:grova_cube_001_dht_ota]
extends = env:grova_cube_001_dht
upload_protocol = espota
upload_port = 192.168.1.70

[env:grova_core_v1]
extends = env:esp32dev
build_flags =
	-D GROVA_BUILD_ENV=\"grova_core_v1\"
	-D GROVA_BOARD_PCB_V1=1
upload_protocol = esptool

[env:grova_core_v1_ota]
extends = env:grova_core_v1
upload_protocol = espota
upload_port = 192.168.1.97

[env:grova_cube_002_bme]
extends = env:esp32dev
build_flags =
	-D GROVA_BUILD_ENV=\"grova_cube_002_bme\"
	-D GROVA_BOARD_PCB_V1=1
	-D GROVA_CUBE_ID_OVERRIDE=\"grova-cube-002\"
	-D OTA_HOSTNAME=\"grova-cube-002\"
upload_protocol = esptool

[env:grova_cube_002_bme_ota]
extends = env:grova_cube_002_bme
upload_protocol = espota
upload_port = 192.168.1.97

[env:grova_core_v1_local]
extends = env:esp32dev
build_flags =
	-D GROVA_BUILD_ENV=\"grova_core_v1_local\"
	-D GROVA_BOARD_PCB_V1=1
	-D GROVA_MQTT_ENABLED=0
upload_protocol = esptool

[env:grova_core_v1_local_ota]
extends = env:grova_core_v1_local
upload_protocol = espota
upload_port = 192.168.1.97

